;{----------------------------------------------------------------------}
;{	math.inc sound definitions					}
;{	COPYRIGHT 1989 Monarch Development				}
;{----------------------------------------------------------------------}

		ifndef	equatesinc
		include	equates.inc
		endif

mathinc		equ	1

		ifndef	dosinc
		include	dos.inc
		endif

;
; -----	global definitions
;

		global	divU32:far

